name: signin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Fustat
      fonts:
        - asset: assets/fonts/Fustat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Fustat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Fustat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Fustat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fustat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fustat-Light.ttf
          weight: 300
        - asset: assets/fonts/Fustat-ExtraLight.ttf
          weight: 200

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: app_assets.dart
  field_prefix: null
