// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUgquTnp41zjX6ZNExxR705jzogWEwgoI',
    appId: '1:1017058501013:web:f035f8c8868f3ed52e169c',
    messagingSenderId: '1017058501013',
    projectId: 'sign-in-with-3963d',
    authDomain: 'sign-in-with-3963d.firebaseapp.com',
    storageBucket: 'sign-in-with-3963d.appspot.com',
    measurementId: 'G-69YXXC3MXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9hwm1P2z-g84BqjD-o6TtQmLuJNXHg70',
    appId: '1:1017058501013:android:4e1888b8ca94d2672e169c',
    messagingSenderId: '1017058501013',
    projectId: 'sign-in-with-3963d',
    storageBucket: 'sign-in-with-3963d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBK_FtmrSTcFhCqky_KndEi8VuCOZ-h1I',
    appId: '1:1017058501013:ios:685750b0ba1c72ea2e169c',
    messagingSenderId: '1017058501013',
    projectId: 'sign-in-with-3963d',
    storageBucket: 'sign-in-with-3963d.appspot.com',
    iosBundleId: 'com.example.signin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBK_FtmrSTcFhCqky_KndEi8VuCOZ-h1I',
    appId: '1:1017058501013:ios:685750b0ba1c72ea2e169c',
    messagingSenderId: '1017058501013',
    projectId: 'sign-in-with-3963d',
    storageBucket: 'sign-in-with-3963d.appspot.com',
    iosBundleId: 'com.example.signin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUgquTnp41zjX6ZNExxR705jzogWEwgoI',
    appId: '1:1017058501013:web:013fc52ce01b76072e169c',
    messagingSenderId: '1017058501013',
    projectId: 'sign-in-with-3963d',
    authDomain: 'sign-in-with-3963d.firebaseapp.com',
    storageBucket: 'sign-in-with-3963d.appspot.com',
    measurementId: 'G-CZB92DKM17',
  );
}
